backend:
  name: git-gateway
  branch: development

media_folder: static/img

collections:
  - label: "Pages"
    name: "pages"
    files:
      - label: "Updates Page"
        name: "updates"
        file: "src/content/updates.json"
        fields:
          - {label: Title, name: title, widget: string}
      - label: "Test Page"
        name: 'test'
        file: "src/content/test/json"
        fields:
          - {label: Title, name: title, widget: string}