backend:
  name: github
  repo: apnerve/mavenhive

media_folder: static/img

collections:
  - label: "Pages"
    name: "pages"
    files:
      - label: "Updates Page"
        name: "updates"
        file: "content/updates.json"
        fields:
          - {label: Title, name: title, widget: string}